version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Redis for Celery broker
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  # Celery worker
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: celery -A celery_app worker --loglevel=info
    depends_on:
      - redis
      - mongodb
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND_URL=redis://redis:6379/1
    volumes:
      - .:/app

  # Celery beat (scheduler)
  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_beat
    command: celery -A celery_app beat --loglevel=info
    depends_on:
      - redis
      - mongodb
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND_URL=redis://redis:6379/1
    volumes:
      - .:/app

  # Optional: Backup logs viewer (for troubleshooting)
  celery_flower:
    image: mher/flower:latest
    container_name: celery_flower
    ports:
      - "5555:5555"
    command: flower --broker=redis://redis:6379/0
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

volumes:
  mongo_data:
